airplay:
        input:
                - 10.16.0.2/12
                - 10.3.0.2/24
        output:
                - 10.16.0.2
                - 10.10.0.2
                - 10.11.0.2
                - 10.13.0.2
        time: 10

airprint:
        input:
                - 10.16.0.2/12
        output:
                - 10.10.0.2
        time: 10
